# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.43.0"
"rocks-config.nvim" = "3.1.0"
"oil.nvim" = "2.14.0"
tree-sitter-c = "scm"
tree-sitter-markdown = "scm"
"nightfox.nvim" = "3.10.0"
nvim-treesitter-textobjects = "scm"
"rocks-dev.nvim" = "1.7.0"
"rocks-git.nvim" = "2.5.2"
luasnip = "2.3.0"
# cmp_luasnip = "scm"
"telescope.nvim" = "scm"
nvim-lspconfig = "1.2.0"
neorg = "9.1.1"
tree-sitter-julia = "scm"
tree-sitter-nix = "scm"
# "image.nvim" = "1.3.0"
semver = "1.2.1"
nvim-treesitter-legacy-api = "0.9.2"
tree-sitter-toml = "scm"
"telescope-ui-select.nvim" = "scm"
tree-sitter-python = "scm"
tree-sitter-latex = "scm"
"lazydev.nvim" = "1.9.0"
# cmp-buffer = "scm"
# cmp-nvim-lsp = "scm"
tree-sitter-glimmer = "0.0.29"

# nvim-smuggler = "0.5"

[plugins."lsp_lines.nvim"]
git = "https://git.sr.ht/~whynothugo/lsp_lines.nvim"
rev = "v3.0.0"

# [plugins.cmp-latex-symbols]
# git = "kdheepak/cmp-latex-symbols"
# rev = "165fb66afdbd016eaa1570e41672c4c557b57124"

# [plugins.cmp-emoji]
# git = "hrsh7th/cmp-emoji"
# rev = "e8398e2adf512a03bb4e1728ca017ffeac670a9f"

# [plugins.friendly-snippets]
# git = "rafamadriz/friendly-snippets"
# rev = "00ebcaa159e817150bd83bfe2d51fa3b3377d5c4"

[plugins.vim-fugitive]
git = "tpope/vim-fugitive"
rev = "v3.7"

# [plugins."pipeline.nvim"]
# git = "topaxi/pipeline.nvim"
# rev = "805d918b0ff0811611a40eaa7a662600900044e8"
# build = "make"

[plugins."hex.nvim"]
git = "raafatturki/hex.nvim"
rev = "fcff75fcf43b5a6c5b471eed65b3a06c412d6020"

[plugins.nvim-smuggler]
git = "klafyvel/nvim-smuggler"
rev = "v0.5.0"

[config]
auto_setup=true
colorscheme="nightfox"
